create table if not exists products (
    identifier INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name varchar(128) NOT NULL,
    price integer,

    PRIMARY KEY (identifier)
);

create table if not exists users (
    identifier INTEGER GENERATED BY DEFAULT AS IDENTITY,
    login varchar(128) NOT NULL,
    password varchar(128) NOT NULL,
    status BOOLEAN DEFAULT FALSE NOT NULL,

    PRIMARY KEY (identifier)
);